### ISSUE TITLE
Fonts with contextual alternates are not correct rendered

### ISSUE THREAD

**Issue by BuZZ-dEE** [corretto/corretto-8#448]
[![Bountysource](https://www.bountysource.com/badge/issue?issue_id=98023722&style=bounties_posted)](https://www.bountysource.com/issues/98023722-fonts-with-contextual-alternates-are-not-correct-rendered?utm_source=Bountysource&utm_medium=shield&utm_campaign=bounties_posted)

Pay attention to the e's, for example:

**Amazon Corretto 8:** _**wrong**_ rendering for font size _**less**_ than _**101**_ and other _**wrong**_ rendering for font size _**greater**_ than _**100**_
![java-8_font_with_contextual_alternates_not_correct_rendering_below_font_size_100](https://user-images.githubusercontent.com/125954/216328603-5417e765-76a8-4870-acb9-a157959fde27.png)

**Amazon Corretto 11-16, 19:** _**wrong**_ rendering for font size _**less**_ than _**101**_ and **correct** rendering for font size **greater** than **100**
![java-19_font_with_contextual_alternates_not_correct_rendering_below_font_size_100](https://user-images.githubusercontent.com/125954/216322739-582e3afa-4a35-4dd0-8c87-56262c626e99.png)

**Example code:**
[FontRederingErrorDemo.zip](https://github.com/AdoptOpenJDK/openjdk-build/files/6325979/FontRederingErrorDemo.zip)

**Fonts with feature contextual alternates:**
- https://bboxtype.com/typefaces/Krikikrak
- http://www.glukfonts.pl/font.php?font=Kleymissky

**OS:**

- Linux:
```
lsb_release -a
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

uname -a
Linux 5.11.15-zen1-2-zen #1 ZEN SMP PREEMPT Sat, 17 Apr 2021 00:22:34 +0000 x86_64 GNU/Linux
```

- Windows 10

It would be great if this could be fixed for OpenJDK 8 (for all sizes).

**Comment by BuZZ-dEE** [comment]
https://github.com/adoptium/adoptium-support/issues/291

**Comment by lutkerd** [comment]
Corretto is using FreeType for the rendering, can you try the tools mentioned on [this page](https://freetype.org/developer.html) to see if this is a problem with FreeType directly? 


> Reporting a Bug
> 
> In case you find a bug, which you think is related to FreeType, please check the problematic font with one of our demo programs, for example ftview or ftstring. In case the problem persists, consult [FreeType's issue list](https://gitlab.freedesktop.org/groups/freetype/-/issues) to find out whether the problem has been reported already. Otherwise, please submit a new issue. It is helpful to use the git version (see above) of FreeType and its demo programs for testing if possible since we don't release FreeType very often.

**Comment by apodtele** [comment]
Unlikely FreeType issue. Do you use HarfBuzz?

**Comment by navyxliu** [comment]
I don't think we can use HarfBuzz in Corretto-8 right now. The integration of HarfBuzz has been delivered in jdk9^[ref](https://openjdk.org/jeps/258) and never get backported to jdk8u. 

I don't think I have sufficient knowledge on this topic. just offer 2 cents I found on internet. it looks like [freetype](https://freetype.sourceforge.net/opentype/index.html) can also handle OpenType Layout.  

>  We are proud to announce that FreeType now supports the OpenType Layout extension tables (also formerly known as TrueType Open). 

if we update our freetype in corretto-8, can we solve this issue?

**Comment by apodtele** [comment]
Wow. You found some really old page and forgot to quote the top warning. :) I am 100% sure that you do not use FreeType 1 because nobody has been for 20 years. 

In a nutshell. FreeType 2 does not do perform *any* text layout. FreeType only reads font files and returns scaled glyph images per client (layout library) request. We simply do not have facilities to interpret contextual variations. You must be using something else for layout.

**Comment by benty-amzn** [comment]
I believe the font layout code resides [here](https://github.com/corretto/corretto-8/tree/develop/jdk/src/share/native/sun/font/layout). I'm not familiar with that part of the codebase, but if this issue impacts multiple vendors and not just Corretto (seems so based on the referenced Adoptium issue), we can consider opening an issue for it at https://bugs.openjdk.org/

**Comment by lutkerd** [comment]
Corretto-11+ on Linux is built to use the bundled lib in the repository so it will use FreeType 2.12.1 and HarfBuzz 4.4.1. 
Corretto-8 will use the system FreeType and I believe the ICU Layout engine (See https://openjdk.org/projects/harfbuzz/).

Corretto-8 and upstream OpenJDK8 are in maintenance mode and are only accepting critical fixes.

In the description you mentioned testing on 11-16 and 19? Did you mean 11-17? If the root cause can be identified we could get it fixed in the tip version of OpenJDK and backported to 17 and 20 which will be the feature release for the next quarterly release.

**Comment by BuZZ-dEE** [comment]
> In the description you mentioned testing on 11-16 and 19? Did you mean 11-17?

No, I have not yet tested it with 17. The issue from [Adoptium](https://github.com/adoptium/adoptium-support/issues/291) was created long ago, the newest version was 16 at that time. Today I tested it with 19 and this issue is still there, so I assume 17 is also affected.

**Comment by BuZZ-dEE** [comment]
> I believe the font layout code resides [here](https://github.com/corretto/corretto-8/tree/develop/jdk/src/share/native/sun/font/layout). I'm not familiar with that part of the codebase, but if this issue impacts multiple vendors and not just Corretto (seems so based on the referenced Adoptium issue), we can consider opening an issue for it at https://bugs.openjdk.org/

@benty-amzn  Yes please, open an issue in [OpenJDK](https://bugs.openjdk.org/). I would do it by myself, but I can not, because I do not have the permissions. It is really a complicated process to get things reported in OpenJDK as an ["Ottonormalverbraucher"](https://www.linguee.de/deutsch-englisch/uebersetzung/dem+ottonormalverbraucher.html).
